draft: rebase to grub-2.12
Failure:

$ fedpkg --release rawhide srpm
$ mock -r fedora-rawhide-x86_64 --no-clean --rebuild grub2-2.12-1.fc41.src.rpm
.
.
.

Don't forget to
  - add "grub-core/lib/gnulib/Makefile" to AC_CONFIG_FILES in ./configure.ac,
  - mention "gnulib" in SUBDIRS in grub-core/lib/Makefile.am,
  - mention "-I m4" in ACLOCAL_AMFLAGS in Makefile.am
    or add an AC_CONFIG_MACRO_DIRS([m4]) invocation in ./configure.ac,
  - mention "m4/gnulib-cache.m4" in EXTRA_DIST in Makefile.am,
  - invoke gl_EARLY in ./configure.ac, right after AC_PROG_CC,
  - invoke gl_INIT in ./configure.ac.
./bootstrap.conf: line 84: grub-core/lib/gnulib-patches/fix-base64.patch: No such file or directory
./bootstrap.conf: line 84: grub-core/lib/gnulib-patches/fix-null-deref.patch: No such file or directory
./bootstrap.conf: line 84: grub-core/lib/gnulib-patches/fix-null-state-deref.patch: No such file or directory
./bootstrap.conf: line 84: grub-core/lib/gnulib-patches/fix-regcomp-uninit-token.patch: No such file or directory
./bootstrap.conf: line 84: grub-core/lib/gnulib-patches/fix-regexec-null-deref.patch: No such file or directory
./bootstrap.conf: line 84: grub-core/lib/gnulib-patches/fix-uninit-structure.patch: No such file or directory
./bootstrap.conf: line 84: grub-core/lib/gnulib-patches/fix-unused-value.patch: No such file or directory
patching file argp-fmtstream.c
.
.
.
+ grep -A100000 '# stuff "make" creates' .gitignore
error: Bad exit status from /var/tmp/rpm-tmp.Cl75kN (%prep)
    Bad exit status from /var/tmp/rpm-tmp.Cl75kN (%prep)

RPM build errors:
Finish: rpmbuild grub2-2.12-1.fc41.src.rpm
Finish: build phase for grub2-2.12-1.fc41.src.rpm
ERROR: Exception(grub2-2.12-1.fc41.src.rpm) Config(fedora-rawhide-x86_64) 0 minutes 35 seconds
INFO: Results and/or logs in: /var/lib/mock/fedora-rawhide-x86_64/result
ERROR: Command failed:
 # /usr/bin/systemd-nspawn -q -M daf81a789592408682fc38d888d7a3b8 -D /var/lib/mock/fedora-rawhide-x86_64/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.thh8umnl:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/fuse --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin '--setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007"' '--setenv=PS1=<mock-chroot> \s-\v\$ ' --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c '/usr/bin/rpmbuild -bb --noclean --target x86_64 --nodeps /builddir/build/SPECS/grub2.spec'